
name: Checking CITATION.cff

on:
  push:
    paths:
      - "CITATION.cff"
  pull_request:
    paths:
      - "CITATION.cff"

jobs:
  cffconvert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: citation-file-format/cffconvert-github-action@2.0.0
        with:
          args: --validate
